server:
  port: 8080
spring:
  datasource:
    name: mysql
    url: jdbc:mysql://192.168.1.245:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver